### ISSUE TITLE
Fatal exception in Android Release

### ISSUE THREAD

**Issue by FufferKS** [splitio/flutter-sdk-plugin#55]
Hi! 
Love the official Split support, integration was really smooth.

However, in release version of the android app, I'm getting a Fatal Exception on startup which kills the app.

```
E/AndroidRuntime(27470): FATAL EXCEPTION: main
E/AndroidRuntime(27470): Process: com.xxx.flutter.dev, PID: 27470
E/AndroidRuntime(27470): java.lang.ExceptionInInitializerError
E/AndroidRuntime(27470): 	at io.split.android.client.storage.db.StorageFactory.getPersistentSplitsStorage(StorageFactory.java:2)
E/AndroidRuntime(27470): 	at g.c.a.a.z.<init>(SplitFactoryImpl.java:76)
E/AndroidRuntime(27470): 	at d.b.a.c.a.e(Unknown Source:3)
E/AndroidRuntime(27470): 	at g.c.b.e.a(SplitFactoryProviderImpl.java:4)
E/AndroidRuntime(27470): 	at g.c.b.m.<init>(SplitWrapperImpl.java:3)
E/AndroidRuntime(27470): 	at g.c.b.j.d(SplitMethodParserImpl.java:85)
E/AndroidRuntime(27470): 	at g.c.b.n.onMethodCall(SplitioPlugin.java:2)
E/AndroidRuntime(27470): 	at g.a.e.a.y.a(MethodChannel.java:2)
E/AndroidRuntime(27470): 	at io.flutter.embedding.engine.n.p.j(DartMessenger.java:1)
E/AndroidRuntime(27470): 	at io.flutter.embedding.engine.n.p.k(DartMessenger.java:2)
E/AndroidRuntime(27470): 	at io.flutter.embedding.engine.n.c.run(Unknown Source:12)
E/AndroidRuntime(27470): 	at android.os.Handler.handleCallback(Handler.java:938)
E/AndroidRuntime(27470): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/AndroidRuntime(27470): 	at android.os.Looper.loopOnce(Looper.java:201)
E/AndroidRuntime(27470): 	at android.os.Looper.loop(Looper.java:288)
E/AndroidRuntime(27470): 	at android.app.ActivityThread.main(ActivityThread.java:7842)
E/AndroidRuntime(27470): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(27470): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
E/AndroidRuntime(27470): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
E/AndroidRuntime(27470): Caused by: java.lang.RuntimeException: Missing type parameter.
E/AndroidRuntime(27470): 	at d.b.d.T.a.getSuperclassTypeParameter(TypeToken.java:5)
E/AndroidRuntime(27470): 	at d.b.d.T.a.<init>(TypeToken.java:2)
E/AndroidRuntime(27470): 	at g.c.a.a.S.f.f.<init>(SqLitePersistentAttributesStorage.java:1)
E/AndroidRuntime(27470): 	at g.c.a.a.S.f.g.<clinit>(SqLitePersistentAttributesStorage.java:1)
E/AndroidRuntime(27470): 	... 19 more
```

**Comment by agustinona** [comment]
Hi @FufferKS we'd like to move this into a support ticket for better tracking. You should receive an email from support@split.io shortly. Please let me know if you don't.

Best,
Agus

**Comment by agustinona** [comment]
For future reference, leaving the solution to this issue here:

1. Create the `proguard-rules.pro` file in the `android/app/` dir.
2. Add the following lines to the `proguard-rules.pro` file
```
-keep class io.split.android.client.dtos.* { *; }
-keep class io.split.android.client.storage.db.** { *; }
-keep public class io.split.android.client.service.sseclient.SseJwtToken.** { *; }
-keep public class io.split.android.client.service.sseclient.SseAuthToken.** { *; }
-keep public class io.split.android.client.service.sseclient.SseAuthenticationResponse.** { *; }
-keep class io.split.android.client.service.sseclient.notifications.** { *; }
-keepattributes Signature
-keep class com.google.gson.reflect.TypeToken { *; }
-keep class * extends com.google.gson.reflect.TypeToken
-keepclassmembers,allowobfuscation class * {
 @com.google.gson.annotations.SerializedName <fields>;
}
```
3. Make sure you are referencing the proguard file in your app's `build.gradle`  (the one in `android/app`), like so:
```
android {
    
    buildTypes {
        release {
            minifyEnabled true
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
            ...
        }
    }
}
```
4. Run `flutter clean` and rebuild.
